/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

public class Dashboard extends javax.swing.JFrame {

    

    public Dashboard() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        dashboardPanel.setLayout(new java.awt.BorderLayout());
        dashboardPanel.add(new DashboardPanel(), java.awt.BorderLayout.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        roundedButtonManageSiswa = new GUI.RoundedButton();
        roundedButtonDashboard = new GUI.RoundedButton();
        roundedButtonSekolah = new GUI.RoundedButton();
        roundedButtonUser = new GUI.RoundedButton();
        roundedButtonLogout = new GUI.RoundedButton();
        roundedButton6 = new GUI.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardPanel.setLayout(null);
        getContentPane().add(dashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1360, 840));

        jPanel1.setBackground(new java.awt.Color(119, 183, 226));

        roundedButtonManageSiswa.setBackground(new java.awt.Color(48, 55, 80));
        roundedButtonManageSiswa.setForeground(new java.awt.Color(255, 255, 255));
        roundedButtonManageSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-manage-24.png"))); // NOI18N
        roundedButtonManageSiswa.setText("Manage Siswa");
        roundedButtonManageSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundedButtonManageSiswa.setIconTextGap(15);
        roundedButtonManageSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButtonManageSiswaActionPerformed(evt);
            }
        });

        roundedButtonDashboard.setBackground(new java.awt.Color(48, 55, 80));
        roundedButtonDashboard.setForeground(new java.awt.Color(255, 255, 255));
        roundedButtonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-home-24 (1).png"))); // NOI18N
        roundedButtonDashboard.setText("Dashboard");
        roundedButtonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundedButtonDashboard.setIconTextGap(15);
        roundedButtonDashboard.setMargin(new java.awt.Insets(2, 14, 3, 18));
        roundedButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButtonDashboardActionPerformed(evt);
            }
        });

        roundedButtonSekolah.setBackground(new java.awt.Color(48, 55, 80));
        roundedButtonSekolah.setForeground(new java.awt.Color(255, 255, 255));
        roundedButtonSekolah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-manage-24.png"))); // NOI18N
        roundedButtonSekolah.setText("Manage Sekolah");
        roundedButtonSekolah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundedButtonSekolah.setIconTextGap(15);
        roundedButtonSekolah.setMaximumSize(new java.awt.Dimension(127, 31));
        roundedButtonSekolah.setMinimumSize(new java.awt.Dimension(127, 31));
        roundedButtonSekolah.setPreferredSize(new java.awt.Dimension(127, 31));
        roundedButtonSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButtonSekolahActionPerformed(evt);
            }
        });

        roundedButtonUser.setBackground(new java.awt.Color(48, 55, 80));
        roundedButtonUser.setForeground(new java.awt.Color(255, 255, 255));
        roundedButtonUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-manage-24.png"))); // NOI18N
        roundedButtonUser.setText("Manage User");
        roundedButtonUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundedButtonUser.setIconTextGap(15);
        roundedButtonUser.setMaximumSize(new java.awt.Dimension(127, 31));
        roundedButtonUser.setMinimumSize(new java.awt.Dimension(127, 31));
        roundedButtonUser.setPreferredSize(new java.awt.Dimension(127, 31));
        roundedButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButtonUserActionPerformed(evt);
            }
        });

        roundedButtonLogout.setBackground(new java.awt.Color(229, 59, 59));
        roundedButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        roundedButtonLogout.setText("Logout");
        roundedButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roundedButtonLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButtonLogout.setRadius(40);
        roundedButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButtonLogoutActionPerformed(evt);
            }
        });

        roundedButton6.setBackground(new java.awt.Color(48, 55, 80));
        roundedButton6.setForeground(new java.awt.Color(255, 255, 255));
        roundedButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-history-24.png"))); // NOI18N
        roundedButton6.setText("History");
        roundedButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundedButton6.setIconTextGap(20);
        roundedButton6.setMaximumSize(new java.awt.Dimension(127, 31));
        roundedButton6.setMinimumSize(new java.awt.Dimension(127, 31));
        roundedButton6.setPreferredSize(new java.awt.Dimension(127, 31));
        roundedButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roundedButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundedButtonSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundedButtonManageSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundedButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundedButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(roundedButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(roundedButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(roundedButtonManageSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(roundedButtonSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(roundedButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(roundedButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(roundedButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundedButtonManageSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButtonManageSiswaActionPerformed
        dashboardPanel.removeAll();
        dashboardPanel.setLayout(new java.awt.BorderLayout());
        dashboardPanel.add(new ManageSiswa(), java.awt.BorderLayout.CENTER);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
    }//GEN-LAST:event_roundedButtonManageSiswaActionPerformed

    private void roundedButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButtonDashboardActionPerformed
        dashboardPanel.removeAll();
        dashboardPanel.setLayout(new java.awt.BorderLayout());
        dashboardPanel.add(new DashboardPanel(), java.awt.BorderLayout.CENTER);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
    }//GEN-LAST:event_roundedButtonDashboardActionPerformed

    private void roundedButtonSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButtonSekolahActionPerformed
        dashboardPanel.removeAll();
        dashboardPanel.setLayout(new java.awt.BorderLayout());
        dashboardPanel.add(new ManageSekolah(), java.awt.BorderLayout.CENTER);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
    }//GEN-LAST:event_roundedButtonSekolahActionPerformed

    private void roundedButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButtonUserActionPerformed
        dashboardPanel.removeAll();
        dashboardPanel.setLayout(new java.awt.BorderLayout());
        dashboardPanel.add(new ManageUser(), java.awt.BorderLayout.CENTER);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
    }//GEN-LAST:event_roundedButtonUserActionPerformed

    private void roundedButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButtonLogoutActionPerformed
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Apakah kamu yakin ingin logout?",
                "Logout",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_roundedButtonLogoutActionPerformed

    private void roundedButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton6ActionPerformed
         dashboardPanel.removeAll();
        dashboardPanel.setLayout(new java.awt.BorderLayout());
        dashboardPanel.add(new LogAbsensi(), java.awt.BorderLayout.CENTER);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
    }//GEN-LAST:event_roundedButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel jPanel1;
    private GUI.RoundedButton roundedButton6;
    private GUI.RoundedButton roundedButtonDashboard;
    private GUI.RoundedButton roundedButtonLogout;
    private GUI.RoundedButton roundedButtonManageSiswa;
    private GUI.RoundedButton roundedButtonSekolah;
    private GUI.RoundedButton roundedButtonUser;
    // End of variables declaration//GEN-END:variables
}
