package GUI;

import com.pemkom.objects.GenericDAO;
import com.pemkom.objects.Sekolah;
import com.pemkom.objects.LogAbsensiView;
import com.pemkom.objects.services.I18nService;
import com.pemkom.objects.services.LogAbsensiService;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;

public class DashboardPanel extends javax.swing.JPanel implements I18nService.I18nChangeListener {

    private GenericDAO<Sekolah> sekolahDAO = new GenericDAO<>("Sekolah", Sekolah.class);
    private LogAbsensiService logAbsensiService = new LogAbsensiService();
    private boolean isInitializing = false;

    public DashboardPanel() {
        initComponents();
        loadDropdownSekolah();
        I18nService.registerListener(this);
        onLanguageChanged();

        // Default: tampilkan data hari ini
        jDateChooser1.setDate(new java.util.Date());
        jDateChooser1.addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName()) && !isInitializing) {
                loadStatistik();
            }
        });
    }

    private void loadDropdownSekolah() {
        isInitializing = true;
        jComboBox1.removeAllItems();
        jComboBox1.addItem(I18nService.get("ui.dropdown.semua")); // default "Semua" / "All"
        List<Sekolah> listSekolah = sekolahDAO.findAll();
        for (Sekolah s : listSekolah) {
            jComboBox1.addItem(s.getNamaSekolah());
        }
        jComboBox1.setSelectedIndex(0);
        isInitializing = false;
        loadStatistik(); // load data awal semua sekolah
    }

    private void loadStatistik() {
        String selectedSekolah = (String) jComboBox1.getSelectedItem();
        String semua = I18nService.get("ui.dropdown.semua");

        boolean isSemuaSekolah = selectedSekolah == null || selectedSekolah.equals(semua)
                || selectedSekolah.equals("Semua") || selectedSekolah.equals("All");
        String sekolahFilter = isSemuaSekolah ? null : selectedSekolah;

        // Ambil semua siswa (total siswa di sekolah terpilih, tidak tergantung tanggal)
        GenericDAO<com.pemkom.objects.Murid> muridDAO
                = new GenericDAO<>("Murid", com.pemkom.objects.Murid.class);
        List<com.pemkom.objects.Murid> semuaMurid;

        if (isSemuaSekolah) {
            semuaMurid = muridDAO.findAll();
        } else {
            semuaMurid = muridDAO.findMany(
                    com.mongodb.client.model.Filters.eq("sekolah", selectedSekolah)
            );
        }
        int total = semuaMurid.size();

        // Tanggal yang dipilih di JDateChooser (default: hari ini)
        LocalDate tanggalDipilih;
        if (jDateChooser1.getDate() != null) {
            tanggalDipilih = jDateChooser1.getDate()
                    .toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();
        } else {
            tanggalDipilih = LocalDate.now();
        }

        // Ambil log absensi pada tanggal terpilih & sekolah terpilih
        List<LogAbsensiView> logTanggalIni
                = logAbsensiService.filterLog(sekolahFilter, null, tanggalDipilih);

        // Hitung UID unik yang berstatus Hadir pada tanggal itu
        java.util.Set<String> sudahAbsen = new java.util.HashSet<>();
        for (LogAbsensiView log : logTanggalIni) {
            if ("Hadir".equalsIgnoreCase(log.getStatus())) {
                sudahAbsen.add(log.getUidRfid());
            }
        }
        int sudah = sudahAbsen.size();

        // Tampilkan ke label di roundedPanel
        lblSudah.setText(String.valueOf(sudah));
        lbltotal.setText(String.valueOf(total));
    }

    @Override
    public void onLanguageChanged() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            jLabel1.setText(I18nService.get("ui.dashboard.header"));
            lbl.setText(I18nService.get("ui.dashboard.sudahAmbil"));

            lbl3.setText(I18nService.get("ui.dashboard.totalSiswa"));

            // Update item pertama dropdown
            isInitializing = true;
            javax.swing.DefaultComboBoxModel<String> model
                    = (javax.swing.DefaultComboBoxModel<String>) jComboBox1.getModel();
            model.removeElementAt(0);
            model.insertElementAt(I18nService.get("ui.dropdown.semua"), 0);
            jComboBox1.setSelectedIndex(0);
            isInitializing = false;

            this.revalidate();
            this.repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbl3 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        roundedPanel1 = new GUI.RoundedPanel();
        lblSudah = new javax.swing.JLabel();
        lblTotal = new GUI.RoundedPanel();
        lbltotal = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1360, 840));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1);
        jLabel1.setBounds(436, 53, 277, 54);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Sekolah", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(377, 133, 420, 64);

        lbl3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Total Siswa");
        add(lbl3);
        lbl3.setBounds(690, 270, 218, 32);

        lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Sudah Mengambil");
        add(lbl);
        lbl.setBounds(250, 280, 218, 32);

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setForeground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setAutoscrolls(true);
        roundedPanel1.setBackgroundColor(new java.awt.Color(237, 238, 252));

        lblSudah.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSudah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSudah.setText("0");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblSudah)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblSudah)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        add(roundedPanel1);
        roundedPanel1.setBounds(240, 330, 226, 145);

        lblTotal.setForeground(new java.awt.Color(237, 238, 252));
        lblTotal.setAutoscrolls(true);
        lblTotal.setBackgroundColor(new java.awt.Color(237, 238, 252));
        lblTotal.setPreferredSize(new java.awt.Dimension(227, 145));

        lbltotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbltotal.setText("0");

        javax.swing.GroupLayout lblTotalLayout = new javax.swing.GroupLayout(lblTotal);
        lblTotal.setLayout(lblTotalLayout);
        lblTotalLayout.setHorizontalGroup(
            lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTotalLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(lbltotal)
                .addGap(88, 88, 88))
        );
        lblTotalLayout.setVerticalGroup(
            lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTotalLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbltotal)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        add(lblTotal);
        lblTotal.setBounds(700, 330, 215, 145);
        add(jDateChooser1);
        jDateChooser1.setBounds(950, 150, 120, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (!isInitializing) {
            loadStatistik();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblSudah;
    private GUI.RoundedPanel lblTotal;
    private javax.swing.JLabel lbltotal;
    private GUI.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
