/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import com.pemkom.objects.services.I18nService;

/**
 *
 * @author LENOVO
 */
public class DashboardPanel extends javax.swing.JPanel implements I18nService.I18nChangeListener {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        I18nService.registerListener(this);
        onLanguageChanged();
    }

    @Override
    public void onLanguageChanged() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            jLabel1.setText(I18nService.get("ui.dashboard.header"));
            jLabel2.setText(I18nService.get("ui.dashboard.sudahAmbil"));
            jLabel3.setText(I18nService.get("ui.dashboard.belumAmbil"));
            jLabel4.setText(I18nService.get("ui.dashboard.totalSiswa"));
            this.revalidate();
            this.repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roundedPanel1 = new GUI.RoundedPanel();
        roundedPanel2 = new GUI.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        roundedPanel3 = new GUI.RoundedPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1360, 840));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1);
        jLabel1.setBounds(436, 53, 277, 54);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Sekolah", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(377, 133, 420, 64);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Siswa");
        add(jLabel4);
        jLabel4.setBounds(880, 280, 218, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sudah Mengambil");
        add(jLabel2);
        jLabel2.setBounds(150, 281, 218, 32);

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setForeground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setAutoscrolls(true);
        roundedPanel1.setBackgroundColor(new java.awt.Color(237, 238, 252));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        add(roundedPanel1);
        roundedPanel1.setBounds(141, 331, 227, 145);

        roundedPanel2.setForeground(new java.awt.Color(237, 238, 252));
        roundedPanel2.setAutoscrolls(true);
        roundedPanel2.setBackgroundColor(new java.awt.Color(237, 238, 252));
        roundedPanel2.setPreferredSize(new java.awt.Dimension(227, 145));

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        add(roundedPanel2);
        roundedPanel2.setBounds(512, 336, 227, 140);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Belum Mengambil");
        add(jLabel3);
        jLabel3.setBounds(509, 281, 218, 32);

        roundedPanel3.setForeground(new java.awt.Color(237, 238, 252));
        roundedPanel3.setAutoscrolls(true);
        roundedPanel3.setBackgroundColor(new java.awt.Color(237, 238, 252));
        roundedPanel3.setPreferredSize(new java.awt.Dimension(227, 145));

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        add(roundedPanel3);
        roundedPanel3.setBounds(890, 340, 215, 140);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private GUI.RoundedPanel roundedPanel1;
    private GUI.RoundedPanel roundedPanel2;
    private GUI.RoundedPanel roundedPanel3;
    // End of variables declaration//GEN-END:variables
}
