/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

// Import tambahan di atas
import com.pemkom.objects.services.LogAbsensiService;
import com.pemkom.objects.LogAbsensiView;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.table.DefaultTableModel;

// Variable di dalam class
public class LogAbsensi extends javax.swing.JPanel {

    private LogAbsensiService service = new LogAbsensiService();
    private DefaultTableModel tableModel;

    public LogAbsensi() {
        initComponents();
        initTabel();
        initDropdownSekolah();
        loadData();
    }

    private void initTabel() {
        tableModel = new DefaultTableModel(
                new String[]{"Nama", "UID RFID", "Sekolah", "Hari", "Jam", "Status"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tblLog.setModel(tableModel);
        tblLog.setRowHeight(28);
    }

    private void initDropdownSekolah() {
        cbSekolah.removeAllItems();
        for (String s : service.getAllSekolah()) {
            cbSekolah.addItem(s);
        }
    }

    private void loadData() {
        // Ambil nilai filter
        String sekolah = (String) cbSekolah.getSelectedItem();
        String nama = txtCariNama.getText().trim();

        // Ambil tanggal dari JDateChooser, null kalau belum dipilih
        LocalDate tanggal = null;
        if (dateChooser.getDate() != null) {
            tanggal = dateChooser.getDate()
                    .toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();
        }

        // Query + filter
        List<LogAbsensiView> data = service.filterLog(sekolah, nama, tanggal);

        // Isi tabel
        tableModel.setRowCount(0);
        for (LogAbsensiView item : data) {
            tableModel.addRow(new Object[]{
                item.getNamaLengkap(),
                item.getUidRfid(),
                item.getSekolah(),
                item.getHari(),
                item.getJam(),
                item.getStatus()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLog = new javax.swing.JTable();
        txtCariNama = new javax.swing.JTextField();
        cbSekolah = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(119, 183, 226));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Riwayat Siswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(1185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1380, 100);

        tblLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLog);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 1260, 490);

        txtCariNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariNamaActionPerformed(evt);
            }
        });
        txtCariNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariNamaKeyReleased(evt);
            }
        });
        add(txtCariNama);
        txtCariNama.setBounds(850, 110, 220, 30);

        cbSekolah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSekolahActionPerformed(evt);
            }
        });
        add(cbSekolah);
        cbSekolah.setBounds(1080, 110, 100, 30);

        btnRefresh.setBackground(new java.awt.Color(0, 204, 51));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-refresh-24.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(1250, 700, 30, 31);

        dateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserPropertyChange(evt);
            }
        });
        add(dateChooser);
        dateChooser.setBounds(1190, 110, 88, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCariNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariNamaActionPerformed

    }//GEN-LAST:event_txtCariNamaActionPerformed

    private void txtCariNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariNamaKeyReleased
        loadData();
    }//GEN-LAST:event_txtCariNamaKeyReleased

    private void cbSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSekolahActionPerformed
        loadData();
    }//GEN-LAST:event_cbSekolahActionPerformed

    private void dateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            loadData();
        }
    }//GEN-LAST:event_dateChooserPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbSekolah;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLog;
    private javax.swing.JTextField txtCariNama;
    // End of variables declaration//GEN-END:variables
}
