/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author LENOVO
 */
public class ManageSiswa extends javax.swing.JPanel {

    /**
     * Creates new form ManageSiswa
     */
    public ManageSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        roundedButtonAdd = new GUI.RoundedButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);
        add(jScrollPane1);
        jScrollPane1.setBounds(-40, 150, 1640, 650);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(20, 50, 140, 40);

        roundedButtonAdd.setBackground(new java.awt.Color(34, 208, 104));
        roundedButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        roundedButtonAdd.setText("Add");
        roundedButtonAdd.setRadius(10);
        roundedButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButtonAddActionPerformed(evt);
            }
        });
        add(roundedButtonAdd);
        roundedButtonAdd.setBounds(180, 50, 100, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Siswa");
        add(jLabel1);
        jLabel1.setBounds(490, 40, 430, 54);
    }// </editor-fold>//GEN-END:initComponents

    private void roundedButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButtonAddActionPerformed
        AddSiswa dialog = new AddSiswa(
                (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
                true
        );
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_roundedButtonAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.RoundedButton roundedButtonAdd;
    // End of variables declaration//GEN-END:variables
}
